version: "3.9"
services:
  nginx:
    image: nginx:1.25
    container_name: meeting_nginx
    ports:
      - "8080:80"               
    volumes:
      - ./public:/var/www/html/public
      - ./admin:/var/www/html/admin
      - ./app:/var/www/html/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [php]
    networks: [mnet]

  php:
    build:
      context: ./docker
      dockerfile: php.Dockerfile
    container_name: meeting_php
    volumes:
      - ./public:/var/www/html/public
      - ./admin:/var/www/html/admin
      - ./app:/var/www/html/app
    depends_on: [db]
    networks: [mnet]

  db:
    image: mysql:8.0
    container_name: meeting_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Bangkok
    ports:
      - "3307:3306"             
    volumes:
     - dbdata:/var/lib/mysql
     - ./sql/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql:ro
     - ./public:/var/www/html/public
     - ./admin:/var/www/html/admin
     - ./app:/var/www/html/app
     - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    networks: [mnet]

  dbgate:
    image: dbgate/dbgate:latest
    container_name: dbgate
    ports:
      - "3000:3000"
    networks: [mnet]
           

networks:
  mnet:

volumes:
  dbdata:
